# Documentation for the Rcoding teaching datasets.
#
# All datasets describe ONE fictional scenario: endemic seasonal malaria in the
# fictional Republic of Amani (a sub-Saharan setting; all place names invented),
# under surveillance across 12 districts over five years (2020-2025). Almost every
# object is derived from the master `case_linelist` and `environment_weekly`.
# Generated by the scripts in data-raw/. All data are simulated for teaching.

# ------------------------------------------------------------------------------
#' Malaria case line-list (master dataset)
#'
#' Individual-level line-list of reported malaria cases in the fictional Republic
#' of Amani over five years. This is the master object from which most other
#' datasets in the package are derived. Transmission is seasonal and rainfall-driven;
#' disease burden and severe outcomes fall most heavily on young children.
#'
#' @format A data frame with 119,757 rows (one per reported case) and 20 variables:
#' \describe{
#'   \item{case_id}{Case identifier, e.g. \code{"M000001"}.}
#'   \item{onset_date, report_date}{Symptom onset and reporting dates (\code{Date}).}
#'   \item{epi_year, epi_week}{Surveillance year and week (1-52) the case is
#'     assigned to (delay-free; the basis for weekly counts).}
#'   \item{age}{Age in years (integer).}
#'   \item{age_group}{5-year age band (factor, \code{"0-4"}...\code{"95-99"}).}
#'   \item{sex}{Factor, \code{"Male"}/\code{"Female"}.}
#'   \item{district}{District of residence (factor, 12 levels).}
#'   \item{facility_id}{Reporting health facility (e.g. \code{"LUS_01"}).}
#'   \item{height_cm, weight_kg}{Anthropometrics.}
#'   \item{ethnicity}{Self-reported ethnicity (character).}
#'   \item{bednet}{Logical: slept under an insecticide-treated net.}
#'   \item{hospitalised, icu}{Logical severity flags.}
#'   \item{admission_date, discharge_date}{Inpatient dates (\code{NA} if not hospitalised).}
#'   \item{outcome}{Factor, \code{"recovered"}/\code{"died"}.}
#'   \item{death_date}{Date of death (\code{NA} unless died).}
#' }
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' head(case_linelist)
#' table(case_linelist$outcome)
#' hist(case_linelist$age, main = "Age of malaria cases")
"case_linelist"

# ------------------------------------------------------------------------------
#' Weekly environmental series by district
#'
#' Weekly rainfall and mean temperature for each district over five years. Rainfall
#' drives malaria transmission with an approximately three-week lag.
#'
#' @format A data frame with 3,120 rows (12 districts x 260 weeks) and 9 variables,
#' including \code{district}, \code{year}, \code{week}, \code{week_start} (\code{Date}),
#' \code{rainfall_mm} and \code{temp_c}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' head(environment_weekly)
"environment_weekly"

# ------------------------------------------------------------------------------
#' Weekly testing and confirmed cases by district
#'
#' Weekly number of malaria tests performed and confirmed cases per district (the
#' denominator behind the line-list).
#'
#' @format A data frame with 3,120 rows and 6 variables: \code{district},
#' \code{year}, \code{week}, \code{week_start}, \code{tested}, \code{cases}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' head(testing_weekly)
"testing_weekly"

# ------------------------------------------------------------------------------
#' Districts of the Republic of Amani
#'
#' One row per district, giving population, region, bednet coverage and a city flag.
#' Two districts (\code{"Lusenga"}, \code{"Mbarako"}) are the focus cities.
#'
#' @format A data frame with 12 rows and 7 variables, including \code{district},
#' \code{region}, \code{is_city}, \code{population}, \code{bednet_coverage}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' districts
"districts"

# ------------------------------------------------------------------------------
#' Health facilities
#'
#' Health facilities per district; facility IDs match \code{facility_id} in
#' \code{case_linelist}.
#'
#' @format A data frame with 35 rows and 2 variables: \code{district}, \code{facility_id}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' head(facilities)
"facilities"

# ------------------------------------------------------------------------------
#' Weekly case counts by age group (matrix)
#'
#' Weekly malaria case counts by 5-year age band over five years. Derived from
#' \code{case_linelist}.
#'
#' @format An integer matrix with 20 rows (age groups) and 260 columns (weeks).
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' dim(incidence_weekly_age)
#' colSums(incidence_weekly_age)[1:6]
"incidence_weekly_age"

# ------------------------------------------------------------------------------
#' Weekly total case counts (vector)
#'
#' National weekly total malaria case counts over five years; equals the column
#' sums of \code{incidence_weekly_age}.
#'
#' @format An integer vector of length 260.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' plot(incidence_weekly, type = "l")
"incidence_weekly"

# ------------------------------------------------------------------------------
#' Patient records (cross-sectional demographic sample)
#'
#' A 150-patient demographic sample drawn from \code{case_linelist}, with
#' deliberately messy column names, for practising data-frame manipulation.
#'
#' @format A data frame with 150 rows and 7 variables: \code{ids}, \code{age},
#' \code{sex}, \code{ht_cm}, \code{wt_kg}, \code{ethnicity}, \code{bednet}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' head(patient_records)
#' table(patient_records$sex)
"patient_records"

# ------------------------------------------------------------------------------
#' Weekly surveillance data for two districts (list)
#'
#' Weekly tests and confirmed cases for the two focus cities, with district-specific
#' column names so that merges use \code{year} and \code{week} as keys.
#'
#' @format A list of two data frames, \code{A} (Lusenga) and \code{B} (Mbarako),
#' each with \code{year}, \code{week}, and district-suffixed \code{tested_} / \code{cases_} columns.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' names(district_weekly_list)
#' head(district_weekly_list$A)
"district_weekly_list"

# ------------------------------------------------------------------------------
#' Allele frequency matrix (loci x samples)
#'
#' Synthetic malaria parasite SNP allele-frequency estimates across loci and
#' samples, including lab artefacts (negative values) and structured missingness,
#' for cleaning practice.
#'
#' @format A numeric matrix with 300 rows (loci) and 200 columns (samples).
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' dim(allele_freq_matrix)
#' sum(is.na(allele_freq_matrix))
#' sum(allele_freq_matrix < 0, na.rm = TRUE)
"allele_freq_matrix"

# ------------------------------------------------------------------------------
#' Drug-resistance marker trajectories (list)
#'
#' Observed prevalence and modelled credible bands for two malaria drug-resistance
#' markers across three sentinel sites over the study period.
#'
#' @format A list of two data frames:
#' \describe{
#'   \item{data}{Observed prevalence at sampling dates: \code{marker}, \code{site},
#'     \code{t}, \code{n_tested}, \code{n_positive}, \code{p_est}, \code{CI_lower}, \code{CI_upper}.}
#'   \item{model}{Modelled credible band on a weekly grid: \code{marker}, \code{site},
#'     \code{t}, \code{Q2.5}, \code{Q25}, \code{Q75}, \code{Q97.5}.}
#' }
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' names(resistance_trajectories)
#' head(resistance_trajectories$data)
"resistance_trajectories"

# ------------------------------------------------------------------------------
#' Bednet coverage vs malaria incidence analysis (list)
#'
#' A bundled analysis object from a village survey relating insecticide-treated net
#' coverage to malaria incidence, for practising work with lists and model outputs.
#'
#' @format A list with three elements:
#' \describe{
#'   \item{data}{Data frame (110 villages) with \code{bednet_coverage} (\%) and
#'     \code{malaria_incidence} (per 1,000 per year).}
#'   \item{summary_stats}{Named numeric vector of means and SDs.}
#'   \item{fit}{An \code{lm} object, \code{malaria_incidence ~ bednet_coverage}.}
#' }
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' names(analysis_bundle)
#' coef(analysis_bundle$fit)
"analysis_bundle"

# ------------------------------------------------------------------------------
#' Posterior density surface (list)
#'
#' A two-dimensional posterior density over two malaria transmission-model
#' parameters, on a regular grid, for practising raster/contour plots and colour scales.
#'
#' @format A list with \code{R0} (x grid), \code{reporting_rate} (y grid) and
#' \code{density} (a matrix of densities).
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' image(posterior_density$R0, posterior_density$reporting_rate, posterior_density$density)
"posterior_density"

# ------------------------------------------------------------------------------
#' Community health worker trial summary
#'
#' Summary results of a community health worker (CHW) intervention trial evaluating
#' time from fever onset to effective malaria treatment, across two service settings.
#'
#' @format A data frame with 4 rows and 4 variables: \code{condition}, \code{group},
#' \code{mean_days_to_treatment}, \code{ci_lower}, \code{ci_upper}.
#' @source Simulated for the Rcoding package (teaching example).
#' @examples
#' chw_trial
"chw_trial"
